# Generated by Django 2.1.1 on 2018-09-02 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('title', models.CharField(choices=[('KI', 'King'), ('QU', 'Queen'), ('DU', 'Duke'), ('CO', 'Count')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('FA', 'Father'), ('MO', 'Mother'), ('BR', 'Brother'), ('SI', 'Sister'), ('FR', 'Friend'), ('SO', 'Son'), ('DA', 'Daughter'), ('MA', 'Master'), ('SE', 'Servant'), ('EN', 'Enemy')], max_length=2)),
                ('object_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_character', to='plays.Character')),
                ('subject_charater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_character', to='plays.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_index', models.IntegerField()),
                ('line_text', models.TextField()),
                ('stage_direction', models.TextField()),
                ('scene_index', models.IntegerField()),
                ('character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plays.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year_published', models.IntegerField()),
                ('genre', models.CharField(choices=[('T', 'Tragedy'), ('C', 'Comedy'), ('H', 'History')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_text', models.TextField()),
                ('number', models.IntegerField()),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plays.Act')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plays.Place')),
            ],
        ),
        migrations.AddField(
            model_name='line',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plays.Scene'),
        ),
        migrations.AddField(
            model_name='character',
            name='play',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plays.Play'),
        ),
        migrations.AddField(
            model_name='act',
            name='play',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plays.Play'),
        ),
    ]
