# Generated by Django 2.1.1 on 2018-09-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='title',
            field=models.CharField(choices=[('KI', 'King'), ('QU', 'Queen'), ('DU', 'Duke'), ('CO', 'Count')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='characterrelationship',
            name='relationship_type',
            field=models.CharField(choices=[('FA', 'Father'), ('MO', 'Mother'), ('BR', 'Brother'), ('SI', 'Sister'), ('FR', 'Friend'), ('SO', 'Son'), ('DA', 'Daughter'), ('MA', 'Master'), ('SE', 'Servant'), ('EN', 'Enemy'), ('CO', 'Cousin'), ('NI', 'Niece'), ('NE', 'Nephew'), ('AU', 'Aunt'), ('UN', 'Uncle')], max_length=2),
        ),
    ]
