# Generated by Django 2.1.1 on 2018-09-02 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0003_auto_20180902_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='play_index',
        ),
    ]
