# Generated by Django 2.1.1 on 2018-09-02 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0006_auto_20180902_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characterrelationship',
            old_name='subject_character',
            new_name='character',
        ),
        migrations.RemoveField(
            model_name='characterrelationship',
            name='object_character',
        ),
        migrations.AddField(
            model_name='characterrelationship',
            name='of_character',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='of_character', to='plays.Character'),
            preserve_default=False,
        ),
    ]
