# Generated by Django 2.1.1 on 2018-09-02 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0008_auto_20180902_2259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationshiptype',
            old_name='counterpart_type',
            new_name='counterpart',
        ),
        migrations.RenameField(
            model_name='relationshiptype',
            old_name='type',
            new_name='feminine',
        ),
        migrations.AddField(
            model_name='relationshiptype',
            name='masculine',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relationshiptype',
            name='relation',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
