# Generated by Django 2.1.1 on 2018-09-02 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0009_auto_20180902_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationshiptype',
            name='feminine',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationshiptype',
            name='masculine',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
