# Generated by Django 2.1.1 on 2018-09-03 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0010_auto_20180902_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterrelationship',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character', to='plays.Character'),
        ),
    ]
