# Generated by Django 2.1.1 on 2018-09-03 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0011_auto_20180903_0009'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='characterrelationship',
            unique_together={('character', 'of_character')},
        ),
    ]
